version: '3'
services:
  db:
    image: postgres:12
    container_name: postgres_db'
    env_file:
      - .env
    restart: unless-stopped
    environment:
      POSTGRES_DB: levart
      POSTGRES_USER: levart2022
      POSTGRES_PASSWORD: levart202
    volumes:
      - ./script/:/docker-entrypoint-initdb.d
      - psql-data:/var/lib/posgresql/data
    ports:
      - "5432:5432"
  php:
   build:
     context: ./docker
     dockerfile: Dockerfile
   image: php_levartech
   container_name: php_engine
   volumes:
     - ./:/var/www/html
   environment:
     CONTAINER_ROLE: app
  redis:
     image: redis
     container_name: container_redis
     env_file:
      - .env
     ports:
       - "6379:6379"

  worker:
    image: app_mail
    container_name: worker
    restart: always
    volumes:
      - ./app/src/:/var/www/html
    command: [ "php", "worker.php" ]